### ISSUE TITLE
Properly handle the lack of the NetworkAttachementDefinition CRD

### ISSUE THREAD

**Issue by ananace** [masayag/foreman_kubevirt#25]
Currently, if multus isn't installed in the cluster, then pages referencing interfaces will fail to render with an unhelpful message.

![screenshot_20190206_115501](https://user-images.githubusercontent.com/534460/52336763-0b580900-2a06-11e9-96a7-e27076bf5fec.png)

The backend error comes out to;

```
ActionView::Template::Error: 404 Not Found
/usr/share/foreman/vendor/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
/usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/resource.rb:51:in `get'
/usr/share/foreman/vendor/ruby/2.3.0/gems/fog-kubevirt-0.2.1/lib/fog/compute/kubevirt.rb:427:in `detect_version'
/usr/share/foreman/vendor/ruby/2.3.0/gems/fog-kubevirt-0.2.1/lib/fog/compute/kubevirt.rb:372:in `create_client_from_token'
/usr/share/foreman/vendor/ruby/2.3.0/gems/fog-kubevirt-0.2.1/lib/fog/compute/kubevirt.rb:357:in `create_client'
/usr/share/foreman/vendor/ruby/2.3.0/gems/fog-kubevirt-0.2.1/lib/fog/compute/kubevirt.rb:449:in `kube_net_client'
/usr/share/foreman/vendor/ruby/2.3.0/gems/fog-kubevirt-0.2.1/lib/fog/compute/kubevirt/requests/list_networkattachmentdefs.rb:6:in `list_networkattachmentdefs'
/usr/share/foreman/vendor/ruby/2.3.0/gems/fog-kubevirt-0.2.1/lib/fog/compute/kubevirt/models/networkattachmentdefs.rb:13:in `all'
```

This should probably instead just result in an empty list of connection points, along with a more helpful error - something along the lines of;
"NetworkAttachementDefinition CRD / Multus is not available in your cluster"

**Comment by masayag** [comment]
With https://github.com/masayag/foreman_kubevirt/pull/53 the user will be able to use the default network only which doesn't require a cni provider. Therefore only 'default' network will be shown on the network list.

There will be a warning in the log indicating there are no network attachment definition installed.
